### ISSUE TITLE
adapt what pressing the back button does in every activity to the expected functionality

### ISSUE THREAD

**Issue by Luca-Engel** [SDPCoachMe/SDP-2023#175]

**Comment by brygotti** [comment]
Suggestions:
You can use "finish()" to quit an Activity when pressing the back button, which goes back to the previous activity that was opened. This would allow for example to not hard-wire the fact that opening a conversation always brings back to the contacts list when clicking on the back button. It would also be good for the schedule activity to have the hamburger menu, as all other "main" activities have.
