### ISSUE TITLE
add location data to the profile (preferred location for the moment)

### ISSUE THREAD

**Issue by Luca-Engel** [SDPCoachMe/SDP-2023#41]
user types an address and that address is stored as gps coordinates in the db

**Comment by brygotti** [comment]
This took me about 5 hours without the tests, but it was only late in the developpement process that I realised that the Google API I was using prevents to use it without having billing information set up in the project. We need to discuss whether we want to implement it using this API or not. For now, the code is in the unmerged branch location-autocomplete.
